### ISSUE TITLE
Compile against older libstdc++

### ISSUE THREAD

**Issue by robfig** [rogchap/v8go#103]
It appears that the bundled `libv8.a` was compiled on a system with the latest versions of shared libraries. Our production environment runs CentOS7, and such new versions are not available without a major upgrade. My impression is that using CentOS in production is a common practice and CentOS7 is not terribly out of date, so I would suspect that this impacts others as well. This is not my area of expertise, though.

Is it a desirable and straightforward to compile libv8.a against older versions? That would allow it to run on a larger variety of systems, and I do not believe that there would be significant drawbacks for users on newer systems. Or, can you think of any workarounds that don't require rebuilding libv8.a or upgrading our production servers?

On deployment, I see these errors:
```
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
```

The system has glibcxx 3.4.19, and it requires 3.4.21:
```
$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

$ ls -l /lib64/libstdc++.so.6
lrwxrwxrwx. 1 root root 19 Dec 21 09:32 /lib64/libstdc++.so.6 -> libstdc++.so.6.0.19
```

**Comment by rogchap** [comment]
The Official Docker image for Go is Debian, so that is our main target.

I'm not aware of many using CentOS TBH.

The main limitation will be the GH linux box for actions as that is where we build the static library for V8 which is `ubuntu-latest`

**Comment by robfig** [comment]
Heh, I did attempt to switch to using a container instead of the raw binary, but I was running into what's probably some bug in the combination of all the Bazel rules that I'm using to build the container, which results in a build where CGO_ENABLED=0. I'll keep investigating that. 

In the meantime, I'm also trying to run the Github actions to build using ubuntu-16.04. It sounds like you wouldn't be keen to have that be upstreamed though, so I'll close this issue. Thanks
