### ISSUE TITLE
Segmentation fault when calling Go func

### ISSUE THREAD

**Issue by arctica** [rogchap/v8go#107]
The below code causes a panic due to a null pointer dereference in goContext() (ctx returned by getContext() seems nil).

```go
package main

import (
	"fmt"

	"rogchap.com/v8go"
)


func main() {
	iso, _ := v8go.NewIsolate()
	global, _ := v8go.NewObjectTemplate(iso)

	printfn, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		fmt.Printf("%+v\n", info.Args())
		return nil
	})

	global.Set("print", printfn, v8go.ReadOnly)


	ctx, _ := v8go.NewContext(iso, global)
	val, _ := ctx.RunScript(`() => { print("foo"); }`, "value.js")
	fn, _ := val.AsFunction()
	val, _ = fn.Call()

	fmt.Printf("result: %+v\n", val)
}
```

```
$ go run test.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x850ed3]

goroutine 1 [running]:
rogchap.com/v8go.goContext(...)
	/home/user/go/pkg/mod/rogchap.com/v8go@v0.5.2-0.20210410040105-4c18ca58a475/context.go:164
rogchap.com/v8go._Cfunc_FunctionCall(0x2c2f3e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:191 +0x4d
rogchap.com/v8go.(*Function).Call.func1(0xc000067f40, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000067e78, 0xc000067ea0, 0x850d15)
	/home/user/go/pkg/mod/rogchap.com/v8go@v0.5.2-0.20210410040105-4c18ca58a475/function.go:28 +0x93
rogchap.com/v8go.(*Function).Call(0xc000067f40, 0x0, 0x0, 0x0, 0x8, 0xc000012320, 0x0)
	/home/user/go/pkg/mod/rogchap.com/v8go@v0.5.2-0.20210410040105-4c18ca58a475/function.go:28 +0x11e
main.main()
	/home/user/dev/foo/test.go:25 +0x1c5
exit status 2
```

**Comment by rogchap** [comment]
Seem's an error in `FunctionCall`, have you double checked the errors are `nil` for `AsFuntion`?

This might be one for @robfig ?

**Comment by arctica** [comment]
The code above is a simplyfied version of the actual code which has error checks. The below code shows the AsFunction() call returns no error.

```go
func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	iso, _ := v8go.NewIsolate()
	global, _ := v8go.NewObjectTemplate(iso)

	printfn, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		fmt.Printf("%+v\n", info.Args())
		return nil
	})

	global.Set("print", printfn, v8go.ReadOnly)


	ctx, err := v8go.NewContext(iso, global)
	check(err)
	val, err := ctx.RunScript(`() => { print("foo"); }`, "value.js")
	check(err)
	fn, err := val.AsFunction()
	check(err)
	val, _ = fn.Call()

	fmt.Printf("result: %+v\n", val)
}
```

**Comment by robfig** [comment]
@rogchap why register and unregister a context around every C call instead of register a Context on creation and unregister it when disposed? This seems sort of error-prone, and a context already has a lifetime that could be used.

**Comment by rogchap** [comment]
@robfig Originally we were using Go `runtime.finalize()` to clean up resources in the C world. So to make sure we can still GC `*Context` we register the context only when we are running a script inside the context and then deregister stright after. This means all callback functions within that lifecycle have access to the `*Context` Go struct.

Now that we don't use finalizers anymore, we have to call `ctx.Close()` so maybe we could do what you say and do it on creation and close/dispose; worth testing this out, agree that it's error-prone; and as a contributor you just "need to know" that you have to do the register/deregister.
