### ISSUE TITLE
Using the same isolate in multiple concurrent go-routines

### ISSUE THREAD

**Issue by cairns19** [rogchap/v8go#120]
I have some code that creates a VM / isolate once, and then pass the isolate into a go routine. Inside this go routine, I create a context from the isolate, and create a new object template.

This works fine for a little while, but then panics (as more than a handful go routines run concurrently). If I pass in a brand new isolate to each instance of the go routine, the panic won't happen.

Am I wrong thinking this ought to work?

**Comment by arctica** [comment]
Isolates (or Contexts) are not goroutine safe. Even in v8 itself they are not threadsafe and require locking.

**Comment by cairns19** [comment]
Thanks for clarifying!
