### ISSUE TITLE
How to access `this` within a function template?

### ISSUE THREAD

**Issue by avidal** [rogchap/v8go#122]
You can use a FunctionTemplate to create a constructor, having it return an instance from an ObjectTemplate.

You can set functions *on* an ObjectTemplate so the object has methods.

But, when someone calls a method (impl as a function template) on an object (from an object template), there's no way that I can see to get access to the object itself from within the method implementation. Are there any examples of something like this actually working?

I started a [thread on slack](https://gophers.slack.com/archives/C01FW4CR5D2/p1618946801073100) but haven't heard anything.

Code example:

```go
package main

import (
	"fmt"

	"rogchap.com/v8go"
)

func main() {
	iso, _ := v8go.NewIsolate()
	g, _ := v8go.NewObjectTemplate(iso)

	ot, err := v8go.NewObjectTemplate(iso)
	if err != nil {
		panic(err)
	}

	fooFn, err := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		// How do I get the instance created in the constructor below?
		fmt.Printf("MyObject.foo(): %q\n", info.Args())
		v, _ := v8go.NewValue(iso, "what is 'this'")
		return v
	})
	if err != nil {
		panic(err)
	}

	if err := ot.Set("foo", fooFn); err != nil {
		panic(err)
	}

	constructor, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		inst, _ := ot.NewInstance(info.Context())
		inst.Set("prop", info.Args()[0])
		return inst.Value
	})

	if err := g.Set("MyObject", constructor); err != nil {
		panic(err)
	}

	ctx, _ := v8go.NewContext(iso, g)

	rv, err := ctx.RunScript(`let x = new MyObject('bar'); x.foo()`, "script.js")
	fmt.Printf("rv: %q, err: %q\n", rv, err)
}
```

**Comment by arctica** [comment]
As far as I can see the current implementation does not expose v8::FunctionCallbackInfo::This() so currently you can't access "this" in a callback. It shouldn't be too difficult to add though.

**Comment by avidal** [comment]
Yeah that's what I had found also; but I have no experience embedding v8 (nor have I done anything with v8go yet) so I wasn't sure if it was just eluding me.

**Comment by uranoxyd** [comment]
In the meantime, you may be able to get the behavior you want by using closures, one example:

```go
package main

import (
	"fmt"

	"rogchap.com/v8go"
)

func main() {
	iso, _ := v8go.NewIsolate()

	newFooFunc, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		internalFoo := new(struct {
			bar string
		})
		internalFoo.bar = "foo"

		printBarFunc, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
			fmt.Println(internalFoo.bar)
			return nil
		})
		setBarFunc, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
			internalFoo.bar = info.Args()[0].String()
			return nil
		})

		clientObj, _ := v8go.NewObjectTemplate(iso)
		clientObj.Set("setBar", setBarFunc)
		clientObj.Set("printBar", printBarFunc)
		obj, _ := clientObj.NewInstance(info.Context())

		return obj.Value
	})

	global, _ := v8go.NewObjectTemplate(iso)
	global.Set("newFoo", newFooFunc)
	ctx, _ := v8go.NewContext(iso, global)

	ctx.RunScript(`
		let a = newFoo();
		let b = newFoo();
		b.setBar("bar");

		a.printBar();
		b.printBar();
	`, "foobar.js")
}
```

The JavaScript-Code:
```javascript
let a = newFoo();
let b = newFoo();
b.setBar("bar");

a.printBar();
b.printBar();
```

Gives output:
```
foo
bar
```

**Comment by avidal** [comment]
@uranoxyd very clever. I had considered that but didn't try it, assuming I couldn't create object templates in the isolate after the context was setup.

**Comment by arctica** [comment]
That's not really getting the receiver object of the method though unless I am missing something. What you might be able to do instead is patch the method from inside JS to add 'this' as the first item in the list of arguments. Something like:

```JS
let x = new MyObject();
let origfunc = x.foo;
x.foo = function() { origfunc.call(this, this, ...arguments };
```

When calling `x.foo(1, 2, 3)` you would get `[x, 1, 2, 3]` from info.Args()

**Comment by uranoxyd** [comment]
@arctica I think I understand your problem. Is ``MyObject`` a class you defined in v8go, since you can instantiate it with ``new``? If yes then I would like to know how to do that :)

**Comment by arctica** [comment]
> @arctica I think I understand your problem. Is `MyObject` a class you defined in v8go, since you can instantiate it with `new`? If yes then I would like to know how to do that :)

I think you ment @avidal
