### ISSUE TITLE
get return from js function

### ISSUE THREAD

**Issue by mohamadpk** [rogchap/v8go#125]
hi i call a function the function in js return a array how i can access to this array on golang?

**Comment by mohamadpk** [comment]
hello you are there??!!

**Comment by echicken** [comment]
@mohamadpk I think you want something along these lines:

```go
ret, _ := fn.Call()
obj, _ := ret.AsObject()
len, _ := obj.Get("length")
_len := len.Int32()
for i := int32(0); i < _len; i++ {
	elem, _ := obj.GetIdx(uint32(i)) // elem would be a v8go.Value
}
```

Pardon my ugly example code.

[See here](https://pkg.go.dev/rogchap.com/v8go#Object) for more on v8go.Object.

**Comment by mohamadpk** [comment]
@echicken tnx.but your code is not work for array .is work for object

**Comment by mohamadpk** [comment]
i read this See here for more on v8go.Object. v8go has a file in library for object but nothing about array

**Comment by mohamadpk** [comment]
i convert my array to object the response is same .this code wont work .tnx

**Comment by echicken** [comment]
In JS an array is an object, just a slightly special one.

The code that I shared above works as expected when I run it here. I am using v8go @ master. You may be getting different results if you are using the latest release of v8go, which is a bit older.

**Comment by echicken** [comment]
Just wanted to follow up with a more complete example:

A go.mod file:

```
module array
go 1.16
require rogchap.com/v8go v0.5.2-0.20210423120543-491864424893
```

The program:

```go
package main

import (
	"fmt"

	"rogchap.com/v8go"
)

func main() {
	ctx, _ := v8go.NewContext()
	val, _ := ctx.RunScript("(() => [1, 2, 3, 4, 5])()", "array")
	obj, _ := val.AsObject()
	len, _ := obj.Get("length")
	_len := len.Int32()
	for i := int32(0); i < _len; i++ {
		elem, _ := obj.GetIdx(uint32(i))
		fmt.Printf("Element %d is %v\r\n", i, elem)
	}
}
```

The output:

```
Element 0 is 1
Element 1 is 2
Element 2 is 3
Element 3 is 4
Element 4 is 5
```

**Comment by mohamadpk** [comment]
yep you is right.fixed.tnx
