### ISSUE TITLE
Why cannot create JavaScript Object from the Object literal

### ISSUE THREAD

**Issue by zhanglianxin** [rogchap/v8go#127]
Hi there. Thanks for your great jobs.

When I try making a new Object from the Object literal, the expected is not going.

Here is the example:

```go
func TestV8(t *testing.T) {
	ctx, _ := v8go.NewContext()
	data := `head=["name", "age"];rows=[];rows[0]=["hello",1];rows[1]=["hi",2];`
	// val, e := ctx.RunScript(data+"[head,rows]", "/")
	val, e := ctx.RunScript(data+`{"head":head,"rows":rows}`, "/") // <nil>  <==HERE
	// val, e := ctx.RunScript(data+"obj={};obj['head']=head;obj['rows']=rows;obj;", "/") // [object Object]
	t.Log(val)
}
```

Help me, please.

**Comment by arctica** [comment]
Your JS code is invalid. You should see the error in `e`. The part where you try to construct the object is interpreted as a code block instead.

**Comment by zhanglianxin** [comment]
> Your JS code is invalid. You should see the error in `e`. The part where you try to construct the object is interpreted as a code block instead.

It should be treated as an Object literal, isn't it?

**Comment by zhanglianxin** [comment]
> > Your JS code is invalid. You should see the error in `e`. The part where you try to construct the object is interpreted as a code block instead.
> 
> It should be treated as an Object literal, isn't it?

Sorry for my fault.  [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#object_literals) is the explanation for **Object literals**. I got it.

@arctica Thanks for your help.

**Comment by zhanglianxin** [comment]
Correct syntax should be:

```diff
- val, e := ctx.RunScript(data+`{"head":head,"rows":rows}`, "/") // <nil>  <==HERE
+ val, e := ctx.RunScript(data+`obj={"head":head,"rows":rows};obj`, "/") // [object Object]
```

**Comment by arctica** [comment]
Yes that is one way. You can also put parenthesis around the curly brackets like:

`({foo: 1, bar: 2})`
