### ISSUE TITLE
Memory leak caused by calling `RunScript` on same context.

### ISSUE THREAD

**Issue by panzhongxian** [rogchap/v8go#150]
```go
package main

import (
	"flag"

	"rogchap.com/v8go"
)

func no_mem_leak() {
	iso, _ := v8go.NewIsolate()     // creates a new JavaScript VM
	ctx1, _ := v8go.NewContext(iso) // new context within the VM
	ctx1.RunScript("const multiply = (a, b) => a * b", "math.js")

	ctx2, _ := v8go.NewContext(iso) // another context on the same VM
	for i := 0; i < 1000000000; i++ {
		if _, err := ctx2.RunScript("multiply(3, 4)", "main.js"); err != nil {
			// this will error as multiply is not defined in this context
		}
	}
}

func mem_leak() {
	iso, _ := v8go.NewIsolate()    // creates a new JavaScript VM
	ctx, _ := v8go.NewContext(iso) // new context within the VM
	ctx.RunScript("const multiply = (a, b) => a * b", "math.js")

	for i := 0; i < 1000000000; i++ {
		if _, err := ctx.RunScript("multiply(3, 4)", "main.js"); err != nil {
			// this will error as multiply is not defined in this context
		}
	}
}

func main() {
	memLeakFlag := flag.Bool("mem_leak", false, "mem_leak")
	flag.Parse()
	if *memLeakFlag {
		mem_leak()
	} else {
		no_mem_leak()
	}
}
```

When I called `RunScript` on same context, a possible memory leak problem may happen. Is this a bug? Or I used the context in a wrong way?

The above code is what I have run. And the memory:

![image](https://user-images.githubusercontent.com/11887422/123806480-9280e100-d921-11eb-9f39-0ccc6ee48ae5.png)

**Comment by dylanahsmith** [comment]
This is the same memory leak as https://github.com/rogchap/v8go/issues/105, although the title of that makes it sound like a more limited.

What is happening is that v8go keeps a reference to all v8go.Value objects that it creates, including the one returned from `RunScript`.  This memory is held onto until the isolate is disposed.

**Comment by panzhongxian** [comment]
Hi, @dylanahsmith . Thanks for your redirection and I saw the full discussion. Hope the implementation will be finished soon.
