### ISSUE TITLE
TerminateExecution does not appear to be terminating execution of isolate

### ISSUE THREAD

**Issue by mcl0vinit** [rogchap/v8go#151]
I'm having an issue where TerminateExecution is not stopping the isolate from continuing to execute the script. I'm using the [v8go polyfill](https://github.com/kuoruan/v8go-polyfills) for setInterval but it does not appear to be interrupting execution of the program. Below is an example of the code I'm using

```
package main

import (
	"log"
	"time"
	"go.kuoruan.net/v8go-polyfills/timers"
	"rogchap.com/v8go"
)

func main() {
	iso, _ := v8go.NewIsolate()
	gbl, _ := v8go.NewObjectTemplate(iso)
	if err := timers.InjectTo(iso, gbl); err != nil {
		panic(err)
	}
	ctx, _ := v8go.NewContext(iso, gbl)
	console, _ := v8go.NewObjectTemplate(iso)
	logfn, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		log.Println(info.Args()[0])
		return nil
	})
	console.Set("log", logfn)
	consoleObj, _ := console.NewInstance(ctx)

	global := ctx.Global()
	global.Set("console", consoleObj)

	script := `setInterval(function() { console.log("interval") }, 3000)`

	errs := make(chan error)

	go func() {
		_, err := ctx.RunScript(script, "")
		if err != nil {
			errs <- err
		}
	}()

	select {
	case err := <-errs:
		log.Println("error found")
		log.Println(err)
	case <-time.After(10 * time.Second):
		iso.TerminateExecution()
		log.Println("terminated")
		err := <-errs
		log.Println(err)
	}
}
```

and I'm getting the result below. You can see that I call TerminateExecution and expect to return an error from RunScript but I never receive it and setInterval continues to run

```
2021/07/05 21:38:14 interval
2021/07/05 21:38:17 interval
2021/07/05 21:38:20 interval
2021/07/05 21:38:21 terminated
2021/07/05 21:38:23 interval
2021/07/05 21:38:26 interval
2021/07/05 21:38:29 interval
```
 
I've also tried getting the isolate from the context as well using ctx.Isolate() but I'm getting the same behavior.

**Comment by arctica** [comment]
I believe this is more a problem with that polyfill package. I don't think the code is correct as Isolates/Contexts are not goroutine safe in v8go but it calls into v8go from a goroutine [0] to run the interval callback. It's own code seems to also contains race conditions when multiple goroutines are used as it uses a package global variable without synchronization. It also seems to ignore any error/exception thrown in the timer callback [1]. A quick glance at that project's 'fetch' polyfill seems to suggest that this part too is suffering from thread safety problems. I suggest you open an issue with that project.

I don't know why the functions are still executed even after the isolate has been terminated though, that's interesting. I mean sure, it ignores the exceptions thrown but one would assume V8 would prevent further execution.

[0] https://github.com/kuoruan/v8go-polyfills/blob/master/timers/internal/item.go#L56
[1] https://github.com/kuoruan/v8go-polyfills/blob/master/timers/timers.go#L144

**Comment by mcl0vinit** [comment]
Understood, I'm new to the project so I wasn't sure if I was missing something that I just wasn't seeing. Thank you for taking a look into it for me, I really appreciate it.
