### ISSUE TITLE
Is there a group for instant communication

### ISSUE THREAD

**Issue by MikeGrateful** [rogchap/v8go#155]
Is there a group for instant communication

**Comment by genevieve** [comment]
There is a v8go slack channel in the gophers slack workspace. https://gophers.slack.com/archives/C01FW4CR5D2

**Comment by MikeGrateful** [comment]
tq

**Comment by MikeGrateful** [comment]
> There is a v8go slack channel in the gophers slack workspace. https://gophers.slack.com/archives/C01FW4CR5D2
> 
> Edit: It's linked to at the top of the readme https://github.com/rogchap/v8go#readme

184377367@qq.com  What does it mean not to be in the workspace？
i need help

**Comment by dylanahsmith** [comment]
Try using https://invite.slack.golangbridge.org/ to get an invite to the gophers slack workspace.

**Comment by dylanahsmith** [comment]
If that works, this issue could be closed, since that is linked to in the README's Support section (https://github.com/rogchap/v8go#support)
