### ISSUE TITLE
Automate upgrading v8 binaries

### ISSUE THREAD

**Issue by genevieve** [rogchap/v8go#165]
https://github.com/rogchap/v8go#upgrading-the-v8-binaries

> This process is non-trivial, and hopefully we can automate more of this in the future.

We should automate the workflow described above so that it can be at least manually run to upgrade v8 to the latest release that chrome uses. This workflow can be used to keep v8 up-to-date as well as ready for when a CVE is detected.

**Comment by tmc** [comment]
100% in agreement, a github action that carries out these steps would be a great addition.

**Comment by GustavoCaso** [comment]
@genevieve I have been toying on how we could automate this process.

We could create a GitHub action that runs using the [on.schedule](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule) trigger. We can configure based on the [release cycle](https://v8.dev/docs/release-process) of v8. 

The workflow would take care of doing all the steps outlined in the guide reference above and ultimately it would create a pull request with a special name, which [would trigger](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) the already existing [build workflow](https://github.com/rogchap/v8go/blob/master/.github/workflows/v8build.yml)

We would need to change the build workflow from `on: workflow_dispatch` to:

```yml
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'v8_new_release' # for example
```

So the fully automated process would involve two different workflows.

@genevieve what do you think about this solution? Is there anything that you would like to change?

**Comment by dylanahsmith** [comment]
It seems like the V8 patches (in [deps/windows_x86_64](https://github.com/rogchap/v8go/tree/8d15ff390bcdb886757ed257a70a99e080a590e9/deps/windows_x86_64)) used to build on windows are going to frequently break on V8 upgrades.

**Comment by genevieve** [comment]
@GustavoCaso Yeah the approach sounds good. Last week I was going on the upgrade to v9.3 and wrote a [script](https://github.com/genevieve/v8go/blob/v9_3_upgrade/upgrade-v8.sh) for the steps described in the readme for building the binaries which looks to also be somewhat covered in the build workflow you linked to.

**Comment by GustavoCaso** [comment]
@genevieve @dylanahsmith I've made some progress towards automating the v8 binary upgrade and build.

I was able to create a GH workflow that pulls the latest code from the stable version and updates the `deps/include` as well the submodule commits, similar to the [script](https://github.com/genevieve/v8go/blob/v9_3_upgrade/upgrade-v8.sh) that @genevieve wrote.

I've done all the testing in my fork, so I wouldn't create too much noise for people.

You can check the workflow for upgrading the v8 binaries [here](https://github.com/GustavoCaso/v8go/blob/master/.github/workflows/v8upgrade.yml)

And [here](https://github.com/GustavoCaso/v8go/pull/20) is an example PR that the workflow opens.

Next week I'm going to try to fix the issues with the window compilation process and try replacing MINGW with [GN](https://v8.dev/docs/build-gn) which would allow having consistent builds for windows.

After that, we can update the workflows as mentioned [here](https://github.com/rogchap/v8go/issues/165#issuecomment-925786533)

**Comment by dylanahsmith** [comment]
> Next week I'm going to try to fix the issues with the window compilation process and try replacing MINGW with [GN](https://v8.dev/docs/build-gn) which would allow having consistent builds for windows.

build.py is already using `gn` to build v8 on windows.  That is just a meta build system, where MinGW is the port of the GNU Compiler Collection (GCC) to compile for windows.

If we can't fully automate the v8 upgrade, perhaps it could at least be partially automated into a v8-next branch, omitting the windows build until it has been fixed for the next version of v8.

**Comment by genevieve** [comment]
Considering this issue closed since Gustavo's PRs have been merged and we have automatic PRs for upgrading v8 that build the binaries across platform and open a PR back to the main upgrade PR for each one. When all the binaries are updated/merged, the tests can be run and the upgrade merged.
