### ISSUE TITLE
Add leak checking to CI

### ISSUE THREAD

**Issue by genevieve** [rogchap/v8go#222]
Instead of trying to [run valgrind](https://github.com/rogchap/v8go/issues/218#issuecomment-961302410) across different platforms, we can conditionally set flags for relevant clang sanitizers on the builds of v8go when we are running tests so that we can automate the checking of any memory/thread leakage (for example.)

We could do the conditional configuration in here: https://github.com/rogchap/v8go/blob/master/cgo.go

Here is an example clang sanitizer: https://clang.llvm.org/docs/LeakSanitizer.html

**Comment by dylanahsmith** [comment]
We don’t need to run the leak detector on all platforms.  It is unlikely that there will be platform specific leaks.  So we could just use valgrind on CI, only on linux.  E.g. we are doing that in a ruby C extension (https://github.com/Shopify/liquid-c/pull/162).

It would just be nicer if we could run the leak checker locally on a non-linux OS, if it can catch leaks just as well.

**Comment by dylanahsmith** [comment]
The new Go release will include Address Sanitizer (https://github.com/golang/go/issues/44853), so we should use that.  It looks like gcc also supports address sanitization, so this isn't actually clang specific as I previously thought.  The address sanitizer normally do a leak check on exit, although even with [gotip](https://pkg.go.dev/golang.org/dl/gotip) that still needs to be done explicitly by calling `__lsan_do_leak_check()`.  What matters is that we should align ourselves with Go's future tooling, which is more likely to have better integration in the future.
