### ISSUE TITLE
Does v8go support sending HTTP requests directly through JS

### ISSUE THREAD

**Issue by E0001** [rogchap/v8go#224]
Does v8go support sending HTTP requests directly through JS

**Comment by dylanahsmith** [comment]
Not by default, but there is an example in the docs showing how this can be done: https://pkg.go.dev/rogchap.com/v8go#example-FunctionTemplate-Fetch

**Comment by E0001** [comment]
> 默认情况下不是，但文档中有一个示例展示了如何做到这一点：[https](https://pkg.go.dev/rogchap.com/v8go#example-FunctionTemplate-Fetch) : [//pkg.go.dev/rogchap.com/v8go#example-FunctionTemplate-Fetch](https://pkg.go.dev/rogchap.com/v8go#example-FunctionTemplate-Fetch)

Thank you. I'll try
