### ISSUE TITLE
How to custom APIs?

### ISSUE THREAD

**Issue by Cretezy** [rogchap/v8go#28]
I'm interesting in adding custom APIs, such as adding a `console` API to print.

My question is how to add callbacks from JS to Go using v8go. I've used J2V8 before which allows to add APIs to the global scope, such as an object for `console` with the method `log` which calls back to Java in that case. Is that possible using this project?

The ideal API would be something like (pseudo code):

```
console = CreateObject()

console.AddMethod("log", (params Value[]) {
	print(params[0])
})

isolate.Add("console", console)
```

In addition, it would be much more useful to actually be able to use `Value` with more than strings.

**Comment by kostya-ten** [comment]
I would also like to get such functionality!

**Comment by protosam** [comment]
Being able to bind structs, functions, and values to variables in V8 would make this useful for the project I'm working on as well. Right now I'm trying to replace goja, and stumbled on this project.

**Comment by tmc** [comment]
Currently this project does not expose a method to influence the global object in the created context.

**Comment by rogchap** [comment]
This is something I'm looking at adding as an API. Starting with #50, which will pave the way for more interop between v8 and Go. 

In terms of specifically `console'log` that may require a slightly custom API as v8 has it's own delegate for the `console` object. Still needs to flesh this out, but will become clearer once I get to that part of the code.

Thanks for your patience.

**Comment by rogchap** [comment]
#64
