### ISSUE TITLE
Global root object don't known about context (this.bar is undefined)

### ISSUE THREAD

**Issue by silentiumNoxe** [rogchap/v8go#280]
https://gist.github.com/silentiumNoxe/aefea0cbd938432dfc1815fe800b30f0

I've found an interesting case with "this" pointer. Gist above shows my tests with the root object.
Example from gist:
```js
const bar = function() { return "hello"}
bar() // hello
this.bar // undefined
```

**Comment by dylanahsmith** [comment]
Seems like that is working the same as in the browser.  E.g. on chrome I get

```
> const bar = 123
undefined
> bar
123
> this.bar
undefined
```

which is exactly what you are seeing.  It looks like global variables in JS don't work the way you think they do, but that isn't a v8go issue.

**Comment by silentiumNoxe** [comment]
oh yes, i'm sory
