### ISSUE TITLE
Run `go get rogchap.com/v8go` is very slow.

### ISSUE THREAD

**Issue by xvrzhao** [rogchap/v8go#31]
Is there any solutions?

**Comment by choonkeat** [comment]
I did a `git clone —depth=1` directly in my GOPATH; much faster

**Comment by xvrzhao** [comment]
> I did a `git clone —depth=1` directly in my GOPATH; much faster

Thanks much. I'll try.

**Comment by rogchap** [comment]
This project includes the V8 pre-built binaries, so you are pulling these every time too. If you are doing CI builds I would suggest caching the results, so you don’t need to pull on every build.

**Comment by xvrzhao** [comment]
Thank you, I've now understood.
