### ISSUE TITLE
how do i convert following python code to golang code via v8go

### ISSUE THREAD

**Issue by aswallz** [rogchap/v8go#320]
Python code
```
import execjs
```

```
with open('./encrypt.js') as f:
    js = execjs.compile(f.read())
    return js.call('Q', urlencode(form_data))
```

```
js.call('getSu',self.username)
```

**Comment by dylanahsmith** [comment]
Translating your code from another language/library seems quite outside the scope of this project, its documentation or github issues.

Please attempt to use documentation (https://pkg.go.dev/rogchap.com/v8go) to try to answer your questions.  If the documentation isn't unclear or lacking in some way, be more specific about that the issue with the documentation.
