### ISSUE TITLE
'v8.h' file not found

### ISSUE THREAD

**Issue by ghoshabhi** [rogchap/v8go#34]
Hello 👋 First of all, thank you for building this library!

I was trying to use this package with my project and received the following error after running `dep ensure`:

```
# <>/<>/<>/forms-api/vendor/rogchap.com/v8go
v8go.cc:3:10: fatal error: 'v8.h' file not found
```

Am I missing any steps ? This is how my `vendor` directory looks after running ensure:
<img width="333" alt="Screen Shot 2020-02-19 at 2 01 35 PM" src="https://user-images.githubusercontent.com/19292575/74880610-6f532400-5320-11ea-97b1-d1895a1c0c69.png">

`dep version` output:
```
dep:
 version     : v0.5.0
 build date  : 2018-08-16
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```

**Comment by ghoshabhi** [comment]
Do I need to compile the v8 build or something ? https://github.com/augustoroman/v8#using-a-pre-compiled-v8 ?

Apologies for not understanding any obvious steps here :/

**Comment by rogchap** [comment]
You shouldn’t need build any of the binaries as the are pre-built.
The issue is with `dep` as it only clones Go code and strips out the c++ header files.

Why are you using `dep` and not the official Go modules?

**Comment by kellyfay94** [comment]
I've run `go mod vendor`, and I get a very similar result.  It doesn't seem to clone the 'deps' folder in the repository.  It keeps all of the C++ header files in the main directory, but not in the subdirectories where the the binaries are.

I'm was using go1.14.4, but upgraded to go1.14.7

**Comment by tmc** [comment]
Please provide a reproducible failing case here. Without that, the issue should be probably just be closed.

**Comment by neptoess** [comment]
@tmc This is pretty easy to reproduce, as, as the repo exists in its current state, there are no `.go` files in the `deps` directory.
As for reproducing it with a test:

1. Create `main.go` with the following contents
```
package main

import "rogchap.com/v8go"

func main() {
	if _, err := v8go.NewIsolate(); err != nil {
		panic(err)
	}
}
```
2. `go mod init`
3. `go mod vendor`
4. Check for the presence of `vendor/rogchap.com/v8go/deps`.

It won't exist, but the entire repo will be present at `$GOPATH/pkg/mod/rogchap.com/v8go`. I mentioned the fix (creating dummy `.go` files in all subdirectories) at the end of #53
