### ISSUE TITLE
How to pass in a DOM?

### ISSUE THREAD

**Issue by abeMedia** [rogchap/v8go#36]
I would like to use this to run tests on a webapp. Is this possible?
To do so I'd need to pass in a DOM (i.e. a HTML page) where all the `<script>` tags are executed, to then check for elements in the DOM.

**Comment by mengweixiang1997** [comment]
You r a genius,  This is not javascript running on the browser.

**Comment by tmc** [comment]
@abeMedia Unfortunately that use case is outside of the scope of this project.

**Comment by zwang** [comment]
@abeMedia  checkout these 3 projects:


https://github.com/wailsapp/wails  (v2 is on the way, supposed to be better, it use a custom webview)
https://github.com/webview/webview (used by wails, but you can use this alone with golang)
https://github.com/zserge/lorca (developed by the same person did webview)

**Comment by abeMedia** [comment]
Thanks @zwang,

If you check out the webview org you'll see I'm actually a member ;)

**Comment by zwang** [comment]
@abeMedia  Haha, nice! what a small world 👍
