### ISSUE TITLE
What to do about absence of maintainers?

### ISSUE THREAD

**Issue by jacques-n** [rogchap/v8go#362]
Hello, it seems like the maintainers of this project are no longer active. Some reasons why I say that:

* No releases since December 2021
* No v8 upgrades since January 12, 2022
* Only two PRs merged in the second half of 2022
* Recent PRs are not having action workflows approved.

It's unfortunate since it is such a great project. I'm hoping it is simply a misreading of the situation/outward signs. We have recently upgraded to the latest version of v8 since it likely has a lot of security fixes on [our fork](https://github.com/sundeck-io/v8go) and proposed [a PR](https://github.com/rogchap/v8go/pull/363) back to the project to update v8. Any chance someone knows the project maintainers and could figure out what their intentions are?

**Comment by fizx** [comment]
Hi @jacques-n,
I'm hopeful that a new round of maintainers are coming soon.  I reached out to @rogchap and @dylanahsmith, and they were amenable to adding some new people.  We have a few volunteers at my company, and it seems like you're making a lot of progress too.

**Comment by fizx** [comment]
Hi @jacques-n, we do have a new round of maintainers.  At least myself, @RGood have joined.  

We're focussing on some memory leaks, and are very interested in the security fixes and V8 updates.
