### ISSUE TITLE
undefined: v8.NewContext

### ISSUE THREAD

**Issue by dream2333** [rogchap/v8go#380]
I'm using win11+wsl2+ ubuntu22.4, I don't know why the library functions don't seem to be imported
![image](https://user-images.githubusercontent.com/39302391/232793846-64c806da-1405-4dcd-9691-8bfbba9df9f2.png)
![image](https://user-images.githubusercontent.com/39302391/232793987-e1d467f9-7f8a-4200-bf67-a9c584ffc17d.png)

**Comment by ondrej-smola** [comment]
Do you have build-essentials/gcc installed (for cgo)?

**Comment by 0x5457** [comment]
For my case, after executing "go env -w CGO_ENABLED='1'" it worked
