### ISSUE TITLE
fatal error: unexpected signal during runtime execution without -race

### ISSUE THREAD

**Issue by matthewmueller** [rogchap/v8go#39]
I was occasionally getting `fatal error: unexpected signal during runtime execution` while running tests using v8.

I think I'm able to reliably reproduce it now. It never shows up if you run `-race`, but always seems to show up without it.

**Comment by tmc** [comment]
Can you provide additional detail to assist in reproducibility here? Ideally you could share a test case or script that demonstrates your failure?
