### ISSUE TITLE
Proposal: create GitHub organization to facilitate more distributed maintenance

### ISSUE THREAD

**Issue by tmc** [rogchap/v8go#41]
This project is great! Many v8 bindings exist and this one is among the best if not the best. To lower burden on @rogchap alone I suggest that the v8go project moves to a GitHub organization and that some maintainer contribution guidelines be established. 

I can't commit for the long run but I'm happy to help get some of this in place over the next couple of months.

Thoughts?

**Comment by philipmuir** [comment]
+1

My team is currently embarking on the journey of building a Golang service around executing Javascript, and v8go is possibly one of the options we will land on.

We understand we are going to need to maintain whatever we pick (at least from a security point of view) and would be dedicating time to update v8 versions.

**Comment by rogchap** [comment]
I'm happy to give core contributors access to this repo.

I'm not against moving this to an Org (maybe the gofrs org?); but would have to possibly change the vanity import URL too.

Would prefer to see more engagement on this repo first before moving.

**Comment by rogchap** [comment]
There has been a lot of progress on this project in the last month, including updating v8 to the latest stable release (8.7).
There are also a number of projects that currently import this project so we should not break there projects by changing the import statement.

As such, I'm in favor of maintaining this repo and closing this issue; is that OK with you @tmc?

I'm happy to revisit this in the future, should the community want to move in that direction, but for now I think it's ok as-is.

Still happy to add any core-contributors to this repo that are actively raising PRs to this project.

**Comment by tmc** [comment]
Sounds good!
