### ISSUE TITLE
Data I/O

### ISSUE THREAD

**Issue by zwass** [rogchap/v8go#45]
Can you help me understand if the following interpretations are correct?

1. The only way to get input data to the script is by printing the data into the script itself.

2. The only way to get output data is from the stringified value of the result of the script.

Are there plans to add additional ways to share values back and forth between Go and V8?

**Comment by rogchap** [comment]
Hey @zwass; thank for reaching out. To answer your first question: yes, that is currently the case.

In terms of further interop: it's something that is currently being explored. It's very early in terms of thinking, and an API design is not fully understood at this stage.

If you are keen to discuss more, or you have ideas you can reach out in Gophers Slack.

**Comment by rogchap** [comment]
FYI: #50

**Comment by rogchap** [comment]
FYI: #59

**Comment by rogchap** [comment]
Now also #64 

I'm going to close this issue in favor of tracking this as part of #28 

Please feel free to Reopen, if you don't feel this has address your question.
