### ISSUE TITLE
Include Windows build of V8

### ISSUE THREAD

**Issue by FabianTe** [rogchap/v8go#7]
Hi,

I'd love to see V8 build be included in the deps.

Is this easily possible?

**Comment by rogchap** [comment]
I'm currently trying to get a CI build happening with GitHub Actions; Once I have this automated for Linux and Mac, I'll try and get a windows version too.

**Comment by rogchap** [comment]
Just a quick update.... I'm trying to get a Windows build of V8 working; but not having much joy.
I'm not a Windows user, nor a python expert. The VM the Github Actions has so many copies of python installed that it has know idea where to look!
If anyone here is an expert with python, virtualenv and Windows, I would appreciate any advice. My efforts can be seen here #23

**Comment by FabianTe** [comment]
I'll give it a try. No promises though.

**Comment by rogchap** [comment]
I’m going to try travisci; and see if there python installation on windows is “cleaner”

**Comment by rogchap** [comment]
So my latest effort where to try and use a docker image running Windows, but it just hangs after the gclient sync command.
I'll try and see if I can run this on a Windows VM on my machine, but this won't be a reproducible CI build (better than nothing).
It's starting to be a lost cause... Another option is to use a *.bat file to do windows, rather than using a python script (although the main issues are using python that v8 uses to build) 🤷‍♂ 
If there are any Window's users that can help, I'd be greatly appreciated.

**Comment by godtoy** [comment]
hi bro, any idea to build for windows ?

**Comment by rogchap** [comment]
Hey @godtoy; I wish I could get this working, but I’ve spent hours and hours trying to get Windows to build, with no success. I’m just not familiar enough with Windows.

If you have some knowledge I would appreciate any assistance? You can view my PR for Windows to see what I have tried. #23

**Comment by godtoy** [comment]
hi I'm trying to compile, and i want to know what's problems you meet , can you show me some error screenshots

**Comment by godtoy** [comment]
Is it  a tool problem?i build v8 success on windows . but i'm not use cgo bindding , so need time to learn how to build cgo link

**Comment by rogchap** [comment]
All the issues I had where building V8 on a Windows VM. If you can get a successful build, great as I can do the rest. All my pain is in the build logs of PR #23

The main issues was dealing with the Windows VM/Containers and the right python tool chain.

**Comment by godtoy** [comment]
hi bro , i build v8 success, but when i build v8go  it throw errors 
![image](https://user-images.githubusercontent.com/13638996/80560620-32886500-8a14-11ea-9e5e-4eff56d85724.png)

any idea to solve this?

**Comment by godtoy** [comment]
i put my v8 build files in windows-x86_64 dir  and then change cgo.go include files

**Comment by rogchap** [comment]
What version of v8 are you building? Current build that v8go is using is 8.0.426.15;
If you are upgrading v8 to a newer version, you may have to update the files in the include folder to the latest version of the header files.

You will also need to add the cgo flags defined in the `cgo.go` file for windows.

**Comment by godtoy** [comment]
that version on branch ```windows-v8-build``` , and i also update include files on this version

**Comment by godtoy** [comment]
hi i find out same slover for v8go . look  rust v8 bindding ```https://github.com/denoland/rusty_v8```

**Comment by godtoy** [comment]
hi, i find out some idea about windows https://github.com/bytecodealliance/wasmtime-go/issues/3

**Comment by jimafisk** [comment]
Hi @rogchap,

Thanks for looking into Windows support! That would be really awesome if it turns out to be feasible. 

Is it correct that v8go will only build with linux GOOS at the moment? I seem to be having the same trouble with darwin as well. Thanks!

**Comment by rogchap** [comment]
Should work fine on Darwin (as that is what I use locally). What errors are you getting on Darwin?

**Comment by jimafisk** [comment]
Oh interesting, I must be doing something wrong. It just seems to think the v8go module I'm importing is undefined. I'm on an Ubuntu 18.04 laptop, but if I try to create a darwin binary with `env GOOS=darwin GOARCH=amd64 go build` it throws an error like "undefined: v8go.Context" at the first reference. I added a screenshot here of what I'm seeing when running the build: https://github.com/rogchap/v8go/issues/38#issuecomment-668135261. Thank you!

**Comment by jimafisk** [comment]
@rogchap I did some testing on another computer, it appears the build is dependent on the computer's OS that you're building from, e.g. you can build a darwin binary on a mac and you can build a linux binary on ubuntu, but you can't build a linux binary on mac or a darwin binary on ubuntu. That's the same issue reported here: https://github.com/rogchap/v8go/issues/35. I'll follow up on that thread since this issue is meant for Windows support. Thanks!

**Comment by mwm-tesla** [comment]
Looks like this is done!: https://github.com/rogchap/v8go/pull/46
