### ISSUE TITLE
Could not set FunctionTemplate to Global Object.

### ISSUE THREAD

**Issue by kuoruan** [rogchap/v8go#85]
Hi @rogchap 
I am writing some polyfills for v8go, but it seems can't set function template to an existing global object:

```
obj := ctx.Global()

fetchFn, _ := v8go.NewFunctionTemplate(iso, f.goFetchSync)
if err := obj.Set("_goFetchSync", fetchFn); err != nil {
    return err
}
```

```
v8go: unsupported object property type `*v8go.FunctionTemplate`
```

https://github.com/rogchap/v8go#update-a-javascript-object-from-go

**Comment by rogchap** [comment]
We would need to implement `GetFunction()` for this to work: https://v8.github.io/api/head/classv8_1_1FunctionTemplate.html#a2e019c10474a4b2352bd1e1cb094f84a

That said, is there a reason why you are not using a `TemplateObject` as your Global Object and setting a function on creation of the Context? There are performance benefits as the template can be cached and re-used to create new contexts.

See here for an example `fetch` API (a very simplified one) that uses a Promise: https://github.com/rogchap/v8go/blob/master/function_template_test.go#L52

**Comment by kuoruan** [comment]
I'm writing a package, which add some polyfills to v8go: #77

Here is my code:

https://github.com/kuoruan/v8go-polyfills

My API is like:

```
ctx, _ := v8go.NewContext()

fetch.Inject(ctx)
console.Inject(ctx)
url.Inject(ctx)
```

**Comment by kuoruan** [comment]
The problem is some polyfills will need to both set global Object and `RunScript`, I can't run script when `Context` is not inited.

**Comment by kuoruan** [comment]
My final purpose is to do React SSR with Go, so I will need many polyfills and they must has the same API in Go server and browser.

Such as the `fetch` API. We will need the Go to write some code to do the http request. But the rest `res.text()`, `res.json()` etc... It is easy to write with JS than Go.

**Comment by Terfender** [comment]
I would love to see an example of bare bone setup for you GO with React SSR with pollyfills.

**Comment by kuoruan** [comment]
Hi @Terfender It's almost done, and I will publish a repo when it is ready.

**Comment by Jarred-Sumner** [comment]
I'd love to see an example as well!

**Comment by Jarred-Sumner** [comment]
I'm curious how ES Module imports would work and things like dynamic imports.

The easiest answer probably is: don't bother, just run esbuild/webpack ahead of time and format the output as an IIFE.

A better answer is something like this: https://stackoverflow.com/questions/52023157/how-would-one-enable-and-use-es6-modules-in-the-v8-javascript-engine/52031275

Looking at the `v8go` code, I don't currently see any uses of `InstantiateModule` or `CompileModule`

**Comment by kuoruan** [comment]
Hi @rogchap

I rewrite the `fetch` API with pure Go code now, https://github.com/kuoruan/v8go-polyfills/tree/master/fetch
It's works fine.

But my problem is, can we get `this` object in the `FunctionTemplate` ?

**Comment by rogchap** [comment]
Are you not able to pass `this` as your first argument?

**Comment by kuoruan** [comment]
So, if I have a cat, the object is like:

```js
const cat = {
    name: "Tom",
    getName: function () {
      return this.name;
    }
}
```

Create a object template for it:

```go
iso, _ := v8go.NewIsolate()
ctx, _ := v8go.NewContext(iso)

cat, err := v8go.NewObjectTemplate(iso)
if err != nil {
	panic(err)
}

getName, err := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
	return nil // get the cat name
})
if err != nil {
	panic(err)
}

if err := cat.Set("getName", getName); err != nil {
	panic(err)
}

myTomCat, err := cat.NewInstance(ctx)
if err != nil {
	panic(err)
}

if err := myTomCat.Set("name", "Tom"); err != nil {
	panic(err)
}
```

because we can't get `this` in the functionTemplate, so I must create new object template for `Tony Cat`, `Jack Cat`...

but it's not a big problem.
