### ISSUE TITLE
windows release dependencies

### ISSUE THREAD

**Issue by zwang** [rogchap/v8go#93]
Hi, has any one tried to release a windows app build with v8go or to send it for testing on non-developer PC? I tried to do that but it will require all the v8 related libraries. I am wondering if anyone has a list of dependencies to be included with the .exe file built. 

I have tried include all the `.dll` libraries in the `C:\msys64\mingw64\bin` folder, the app build still does not run (crash immediately after started). 

Any help is appreciated. Thank you.

**Comment by rogchap** [comment]
I wonder if @neptoess has any clues? This is not my area of expertise.

**Comment by zwang** [comment]
Thanks @rogchap 

I just figured it out. My problem is not related to the dependencies of v8. It is a different issue. 

And regarding the minimum v8 dependencies in windows, here are the 11 .dll files needed for the app to run for me. (All copied from  `C:\msys64\mingw64\bin`)

![Capture](https://user-images.githubusercontent.com/1171212/111721493-3b954700-881d-11eb-98a3-a2d4fc303225.PNG)

**Comment by neptoess** [comment]
@zwang 
Thanks for showing the dependencies. Out of curiosity, do those all show when you run the MinGW ntldd on your compiled Go binary?

**Comment by zwang** [comment]
Hi @neptoess , 

I actually don't know the `ntldd` tool until you mentioned it. I used a dumb way to figure this out. I copied all the `.dll` files in `Mingw64/bin` folder to the same folder of the `.exe` file, then run it. While it is running, I will try to delete all the `.dll` files copied over. For the files being used, windows will not allow me to delete it. So the ones kept are the ones needed.
