### ISSUE TITLE
memory management

### ISSUE THREAD

**Issue by huangjingfang** [rogchap/v8go#94]
Hi,
I've been playing v8go recently, it is definitely the best JS engine I've used .
but when I run a benchmark, I found the memory consumption increase as time goes on. Here's my code :

``` 
const script = `
	const process = (record) => {
		const res = [];
		for (let [k, v] of Object.entries(record)) {
			res.push({
				name: k,
				value: v,
			});
		}
		return JSON.stringify(res);
	};
`

func makeObject() interface{} {
	return map[string]interface{}{
		"a": rand.Intn(1000000),
		"b": "AAAABBBBAAAABBBBAAAABBBBAAAABBBBAAAABBBB",
	}
}

func BenchmarkV8go(b *testing.B) {
	defer func() {
		if e := recover(); e != nil {
			b.Logf("err:%v", e)
		}
	}()
	b.ReportAllocs()
	ctx, _ := v8go.NewContext()
	lock := sync.Mutex{}
	for i := 0; i < b.N; i++ {
		lock.Lock()
		ctx.RunScript(script, "")
		str, _ := json.Marshal(makeObject())
		cmd := fmt.Sprintf("process(%s)", str)
		ctx.RunScript(cmd, "")
		lock.Unlock()
	}
}
```

the code mostly from #25, but what confuse me most is the JS engine only run one JS function repeatedly, why its memory consumption grows  so fast and finally out of memory.  is there a possible memory leak or just because I didn't use it correctly

**Comment by rogchap** [comment]
The memory usage of the values created are tied to the Context. You need to call `ctx.Close()` to free the memory.

**Comment by zhujinhe** [comment]
>  You need to call `ctx.Close()` to free the memory.

It would be nice to add these to the examples in readme.
